<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EpisodeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('episodes')->insert([
            [
                'title' => '1 серия',
                'description' => 'Аста и Юно',
                'slug' => 'episode-1',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3096087&autoplay=0&share=0',
            ],
            [
                'title' => '2 серия',
                'description' => 'Клятва',
                'slug' => 'episode-2',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3096098&autoplay=0&share=0',
            ],
            [
                'title' => '3 серия',
                'description' => 'Вперёд, в столицу Клевера!',
                'slug' => 'episode-3',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3096103&autoplay=0&share=0',
            ],
            [
                'title' => '4 серия',
                'description' => 'Смотровой экзамен в Орден рыцарей чар',
                'slug' => 'episode-4',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3101691&autoplay=0&share=0',
            ],
            [
                'title' => '5 серия',
                'description' => 'Путь к титулу Короля-чародея',
                'slug' => 'episode-5',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3115241&autoplay=0&share=0',
            ],
            [
                'title' => '6 серия',
                'description' => 'Черные Быки',
                'slug' => 'episode-6',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3128208&autoplay=0&share=0',
            ],
            [
                'title' => '7 серия',
                'description' => 'Рекрут номер два',
                'slug' => 'episode-7',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3133853&autoplay=0&share=0',
            ],
            [
                'title' => '8 серия',
                'description' => 'Вперёд на первую миссию!',
                'slug' => 'episode-8',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3139456&autoplay=0&share=0',
            ],
            [
                'title' => '9 серия',
                'description' => 'Зверьё',
                'slug' => 'episode-9',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3150747&autoplay=0&share=0',
            ],
            [
                'title' => '10 серия',
                'description' => 'Защитники',
                'slug' => 'episode-10',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3158753&autoplay=0&share=0',
            ],
            [
                'title' => '11 серия',
                'description' => 'Что произошло в Касл-Тауне?',
                'slug' => 'episode-11',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3181432&autoplay=0&share=0',
            ],
            [
                'title' => '12 серия',
                'description' => 'То, что увидел Король-чародей',
                'slug' => 'episode-12',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3187478&autoplay=0&share=0',
            ],
            [
                'title' => '13 серия',
                'description' => 'То, что увидел Король-чародей, Продолжение',
                'slug' => 'episode-13',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3192722&autoplay=0&share=0',
            ],
            [
                'title' => '14 серия',
                'description' => 'Подземелье',
                'slug' => 'episode-14',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3200839&autoplay=0&share=0',
            ],
            [
                'title' => '15 серия',
                'description' => 'Алмазный чародей',
                'slug' => 'episode-15',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3208327&autoplay=0&share=0',
            ],
            [
                'title' => '16 серия',
                'description' => 'Друзья',
                'slug' => 'episode-16',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3216144&autoplay=0&share=0',
            ],
            [
                'title' => '17 серия',
                'description' => 'Разрушитель',
                'slug' => 'episode-17',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3219932&autoplay=0&share=0',
            ],
            [
                'title' => '18 серия',
                'description' => 'Воспоминания о тебе',
                'slug' => 'episode-18',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3225464&autoplay=0&share=0',
            ],
            [
                'title' => '19 серия',
                'description' => 'Разрушение и спасение',
                'slug' => 'episode-19',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3231486&autoplay=0&share=0',
            ],
            [
                'title' => '20 серия',
                'description' => 'Собрание в Королевской Столице',
                'slug' => 'episode-20',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3235550&autoplay=0&share=0',
            ],
            [
                'title' => '21 серия',
                'description' => 'Бунт в столице',
                'slug' => 'episode-21',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3240264&autoplay=0&share=0',
            ],
            [
                'title' => '22 серия',
                'description' => 'Безумная пляска чар',
                'slug' => 'episode-22',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3252265&autoplay=0&share=0',
            ],
            [
                'title' => '23 серия',
                'description' => 'Багряный король-лев',
                'slug' => 'episode-23',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3256850&autoplay=0&share=0',
            ],
            [
                'title' => '24 серия',
                'description' => 'Пропажа',
                'slug' => 'episode-24',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3261882&autoplay=0&share=0',
            ],
            [
                'title' => '25 серия',
                'description' => 'Беда',
                'slug' => 'episode-25',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3267346&autoplay=0&share=0',
            ],
            [
                'title' => '26 серия',
                'description' => 'Раненые звери',
                'slug' => 'episode-26',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3272593&autoplay=0&share=0',
            ],
            [
                'title' => '27 серия',
                'description' => 'Свет',
                'slug' => 'episode-27',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3278747&autoplay=0&share=0',
            ],
            [
                'title' => '28 серия',
                'description' => 'Всем сердцем',
                'slug' => 'episode-28',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3294896&autoplay=0&share=0',
            ],
            [
                'title' => '29 серия',
                'description' => 'Путь',
                'slug' => 'episode-29',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3294905&autoplay=0&share=0',
            ],
            [
                'title' => '30 серия',
                'description' => 'Зеркальный волшебник',
                'slug' => 'episode-30',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3295640&autoplay=0&share=0',
            ],
            [
                'title' => '31 серия',
                'description' => 'Погоня сквозь снега',
                'slug' => 'episode-31',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3300100&autoplay=0&share=0',
            ],
            [
                'title' => '32 серия',
                'description' => 'Три листа бутона',
                'slug' => 'episode-32',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3304856&autoplay=0&share=0',
            ],
            [
                'title' => '33 серия',
                'description' => 'Помогать кому-нибудь когда-нибудь',
                'slug' => 'episode-33',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3309753&autoplay=0&share=0',
            ],
            [
                'title' => '34 серия',
                'description' => 'Битва магии. Свет против тьмы!',
                'slug' => 'episode-34',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3324910&autoplay=0&share=0',
            ],
            [
                'title' => '35 серия',
                'description' => 'Свет правосудия',
                'slug' => 'episode-35',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3341557&autoplay=0&share=0',
            ],
            [
                'title' => '36 серия',
                'description' => 'Третий глаза',
                'slug' => 'episode-36',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3345947&autoplay=0&share=0',
            ],
            [
                'title' => '37 серия',
                'description' => 'Тот, в ком нет магии',
                'slug' => 'episode-37',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3350454&autoplay=0&share=0',
            ],
            [
                'title' => '38 серия',
                'description' => 'Совещание капитанов',
                'slug' => 'episode-38',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3381689&autoplay=0&share=0',
            ],
            [
                'title' => '39 серия',
                'description' => 'Троекратный салют',
                'slug' => 'episode-39',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3386645&autoplay=0&share=0',
            ],
            [
                'title' => '40 серия',
                'description' => 'История Чёрного Пляжа',
                'slug' => 'episode-40',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3391328&autoplay=0&share=0',
            ],
            [
                'title' => '41 серия',
                'description' => 'Рост Водяной Девы',
                'slug' => 'episode-41',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3396835&autoplay=0&share=0',
            ],
            [
                'title' => '42 серия',
                'description' => 'Подводный Храм',
                'slug' => 'episode-42',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3402392&autoplay=0&share=0',
            ],
            [
                'title' => '43 серия',
                'description' => 'Королевская битва при Храме!',
                'slug' => 'episode-43',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3408508&autoplay=0&share=0',
            ],
            [
                'title' => '44 серия',
                'description' => 'Глупый огненный шар и необузданная молния',
                'slug' => 'episode-44',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3412734&autoplay=0&share=0',
            ],
            [
                'title' => '45 серия',
                'description' => 'Человек, который не умеет останавливаться',
                'slug' => 'episode-45',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3417256&autoplay=0&share=0',
            ],
            [
                'title' => '46 серия',
                'description' => 'Пробуждение!',
                'slug' => 'episode-46',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3421690&autoplay=0&share=0',
            ],
            [
                'title' => '47 серия',
                'description' => 'Единственное средство',
                'slug' => 'episode-47',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3428679&autoplay=0&share=0',
            ],
            [
                'title' => '48 серия',
                'description' => 'Отчаяние против надежды',
                'slug' => 'episode-48',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3434070&autoplay=0&share=0',
            ],
            [
                'title' => '49 серия',
                'description' => 'За пределами',
                'slug' => 'episode-49',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3438317&autoplay=0&share=0',
            ],
            [
                'title' => '50 серия',
                'description' => 'Конец битве, конец отчаянию!',
                'slug' => 'episode-50',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3451166&autoplay=0&share=0',
            ],
            [
                'title' => '51 серия',
                'description' => 'Доказательство правоты',
                'slug' => 'episode-51',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3456361&autoplay=0&share=0',
            ],
            [
                'title' => '52 серия',
                'description' => 'Побеждает сильнейший',
                'slug' => 'episode-52',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3461822&autoplay=0&share=0',
            ],
            [
                'title' => '53 серия',
                'description' => 'Под маской',
                'slug' => 'episode-53',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3464874&autoplay=0&share=0',
            ],
            [
                'title' => '54 серия',
                'description' => 'Больше никогда!..',
                'slug' => 'episode-54',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3469550&autoplay=0&share=0',
            ],
            [
                'title' => '55 серия',
                'description' => 'Человек по имени Фанзель',
                'slug' => 'episode-55',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3473982&autoplay=0&share=0',
            ],
            [
                'title' => '56 серия',
                'description' => 'Человек по имени Фанзель: Продолжение',
                'slug' => 'episode-56',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3478470&autoplay=0&share=0',
            ],
            [
                'title' => '57 серия',
                'description' => 'Проникновение',
                'slug' => 'episode-57',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3482490&autoplay=0&share=0',
            ],
            [
                'title' => '58 серия',
                'description' => 'Решение на поле боя!',
                'slug' => 'episode-58',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3486750&autoplay=0&share=0',
            ],
            [
                'title' => '59 серия',
                'description' => 'Пламя ненависти',
                'slug' => 'episode-59',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3490598&autoplay=0&share=0',
            ],
            [
                'title' => '60 серия',
                'description' => 'Искупление перебежчиков',
                'slug' => 'episode-60',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3494652&autoplay=0&share=0',
            ],
            [
                'title' => '61 серия',
                'description' => 'Обещанный мир',
                'slug' => 'episode-61',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3498946&autoplay=0&share=0',
            ],
            [
                'title' => '62 серия',
                'description' => 'Лучше друг друга',
                'slug' => 'episode-62',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3503573&autoplay=0&share=0',
            ],
            [
                'title' => '63 серия',
                'description' => 'Ничего! Никогда!',
                'slug' => 'episode-63',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3508781&autoplay=0&share=0',
            ],
            [
                'title' => '64 серия',
                'description' => 'Красная нить судьбы',
                'slug' => 'episode-64',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3513212&autoplay=0&share=0',
            ],
            [
                'title' => '65 серия',
                'description' => 'Я дома',
                'slug' => 'episode-65',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3523622&autoplay=0&share=0',
            ],
            [
                'title' => '66 серия',
                'description' => 'Секрет Глаза Белой Ночи',
                'slug' => 'episode-66',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3530063&autoplay=0&share=0',
            ],
            [
                'title' => '67 серия',
                'description' => 'Веселый фестиваль двойных свиданий',
                'slug' => 'episode-67',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3534501&autoplay=0&share=0',
            ],
            [
                'title' => '68 серия',
                'description' => 'Битва на смерть!? Ями против Джека',
                'slug' => 'episode-68',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3539683&autoplay=0&share=0',
            ],
            [
                'title' => '69 серия',
                'description' => 'Меланхолия Девы Роз',
                'slug' => 'episode-69',
                'video_code' => '/https://video.sibnet.ru/shell.php?videoid=3543622&autoplay=0&share=0',
            ],
            [
                'title' => '70 серия',
                'description' => 'Две новые звезды',
                'slug' => 'episode-70',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3548587&autoplay=0&share=0',
            ],
            [
                'title' => '71 серия',
                'description' => 'Некоронованная, непобедимая львица',
                'slug' => 'episode-71',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3552887&autoplay=0&share=0',
            ],
            [
                'title' => '72 серия',
                'description' => 'Огни святого Эльма',
                'slug' => 'episode-72',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3558155&autoplay=0&share=0',
            ],
            [
                'title' => '73 серия',
                'description' => 'Отборочный экзамен рыцарей-чародеев',
                'slug' => 'episode-73',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3563429&autoplay=0&share=0',
            ],
            [
                'title' => '74 серия',
                'description' => 'Цветы революции',
                'slug' => 'episode-74',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3567997&autoplay=0&share=0',
            ],
            [
                'title' => '75 серия',
                'description' => 'Ожесточенный бой',
                'slug' => 'episode-75',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3573719&autoplay=0&share=0',
            ],
            [
                'title' => '76 серия',
                'description' => 'Маг X',
                'slug' => 'episode-76',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3578713&autoplay=0&share=0',
            ],
            [
                'title' => '77 серия',
                'description' => 'Грязная кровь',
                'slug' => 'episode-77',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3585327&autoplay=0&share=0',
            ],
            [
                'title' => '78 серия',
                'description' => 'Ловушка простолюдина',
                'slug' => 'episode-78',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3589617&autoplay=0&share=0',
            ],
            [
                'title' => '79 серия',
                'description' => 'Хулиган старшой против качка-дуралея',
                'slug' => 'episode-79',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3594324&autoplay=0&share=0',
            ],
            [
                'title' => '80 серия',
                'description' => 'Одарённый младший против неудачника старшего',
                'slug' => 'episode-80',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3598809&autoplay=0&share=0',
            ],
            [
                'title' => '81 серия',
                'description' => 'Жизнь одного замечательного человека',
                'slug' => 'episode-81',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3603125&autoplay=0&share=0',
            ],
            [
                'title' => '82 серия',
                'description' => 'Клеверочек!! Ночной кошмар Чарми!',
                'slug' => 'episode-82',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3608146&autoplay=0&share=0',
            ],
            [
                'title' => '83 серия',
                'description' => 'Сейчас я сожгу тебя',
                'slug' => 'episode-83',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3612632&autoplay=0&share=0',
            ],
            [
                'title' => '84 серия',
                'description' => 'Победители',
                'slug' => 'episode-84',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3616684&autoplay=0&share=0',
            ],
            [
                'title' => '85 серия',
                'description' => 'Разговор по душам',
                'slug' => 'episode-85',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3622428&autoplay=0&share=0',
            ],
            [
                'title' => '86 серия',
                'description' => 'Ями и Ванджанс',
                'slug' => 'episode-86',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3626331&autoplay=0&share=0',
            ],
            [
                'title' => '87 серия',
                'description' => 'Рыцари Короны',
                'slug' => 'episode-87',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3631490&autoplay=0&share=0',
            ],
            [
                'title' => '88 серия',
                'description' => 'Вперёд на штурм укрытия Глаза Белой Ночи!',
                'slug' => 'episode-88',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3635378&autoplay=0&share=0',
            ],
            [
                'title' => '89 серия',
                'description' => 'Пристанище Чёрных Быков',
                'slug' => 'episode-89',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3639926&autoplay=0&share=0',
            ],
            [
                'title' => '90 серия',
                'description' => 'Сумасшедшая магическая битва',
                'slug' => 'episode-90',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3644517&autoplay=0&share=0',
            ],
            [
                'title' => '91 серия',
                'description' => 'Мереолеона против Райи Неверного',
                'slug' => 'episode-91',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3648466&autoplay=0&share=0',
            ],
            [
                'title' => '92 серия',
                'description' => 'Король Магов против лидера Глаза Белой Ночи',
                'slug' => 'episode-92',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3652290&autoplay=0&share=0',
            ],
            [
                'title' => '93 серия',
                'description' => 'Юлиус Новахроно',
                'slug' => 'episode-93',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3656839&autoplay=0&share=0',
            ],
            [
                'title' => '94 серия',
                'description' => 'Новое будущее',
                'slug' => 'episode-94',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3664299&autoplay=0&share=0',
            ],
            [
                'title' => '95 серия',
                'description' => 'Реинкарнация',
                'slug' => 'episode-95',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3668864&autoplay=0&share=0',
            ],
            [
                'title' => '96 серия',
                'description' => 'Капитан Чёрных быков против Алой розы',
                'slug' => 'episode-96',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3672854&autoplay=0&share=0',
            ],
            [
                'title' => '97 серия',
                'description' => 'Всесокрушающая слабость',
                'slug' => 'episode-97',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3678050&autoplay=0&share=0',
            ],
            [
                'title' => '98 серия',
                'description' => 'Спящий Лев',
                'slug' => 'episode-98',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3688681&autoplay=0&share=0',
            ],
            [
                'title' => '99 серия',
                'description' => 'Отчаянный путь к выживанию',
                'slug' => 'episode-99',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3692613&autoplay=0&share=0',
            ],
            [
                'title' => '100 серия',
                'description' => 'Мы вам не проиграем',
                'slug' => 'episode-100',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3697738&autoplay=0&share=0',
            ],
            [
                'title' => '101 серия',
                'description' => 'Жители отдалённой деревни',
                'slug' => 'episode-101',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3703996&autoplay=0&share=0',
            ],
            [
                'title' => '102 серия',
                'description' => 'Два чуда',
                'slug' => 'episode-102',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3707498&autoplay=0&share=0',
            ],
            [
                'title' => '103 серия',
                'description' => 'Высвобождение проклятого',
                'slug' => 'episode-103',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3711568&autoplay=0&share=0',
            ],
            [
                'title' => '104 серия',
                'description' => 'Яростная молния против друзей',
                'slug' => 'episode-104',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3718271&autoplay=0&share=0',
            ],
            [
                'title' => '105 серия',
                'description' => 'Улыбка и слёзы',
                'slug' => 'episode-105',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3722383&autoplay=0&share=0',
            ],
            [
                'title' => '106 серия',
                'description' => 'Путь мести, путь искупления',
                'slug' => 'episode-106',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3727142&autoplay=0&share=0',
            ],
            [
                'title' => '107 серия',
                'description' => 'Битва за Замок Клевера',
                'slug' => 'episode-107',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3732677&autoplay=0&share=0',
            ],
            [
                'title' => '108 серия',
                'description' => 'Танцовщица на поле боя',
                'slug' => 'episode-108',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3739250&autoplay=0&share=0',
            ],
            [
                'title' => '109 серия',
                'description' => 'Братья пространственной магии',
                'slug' => 'episode-109',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3744338&autoplay=0&share=0',
            ],
            [
                'title' => '110 серия',
                'description' => 'Буйный бык, вперёд, в решительный бой!!',
                'slug' => 'episode-110',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3752852&autoplay=0&share=0',
            ],
            [
                'title' => '111 серия',
                'description' => 'Взгляд со стороны зеркала',
                'slug' => 'episode-111',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3758733&autoplay=0&share=0',
            ],
            [
                'title' => '112 серия',
                'description' => 'Люди, которым можно верить',
                'slug' => 'episode-112',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3763920&autoplay=0&share=0',
            ],
            [
                'title' => '113 серия',
                'description' => 'Штурм дворца теней',
                'slug' => 'episode-113',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3768861&autoplay=0&share=0',
            ],
            [
                'title' => '114 серия',
                'description' => 'Последний зритель',
                'slug' => 'episode-114',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3773361&autoplay=0&share=0',
            ],
            [
                'title' => '115 серия',
                'description' => 'Кукловод',
                'slug' => 'episode-115',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3777659&autoplay=0&share=0',
            ],
            [
                'title' => '116 серия',
                'description' => 'Заклятый враг',
                'slug' => 'episode-116',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3792373&autoplay=0&share=0',
            ],
            [
                'title' => '117 серия',
                'description' => 'Пора снять печать',
                'slug' => 'episode-117',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3804331&autoplay=0&share=0',
            ],
            [
                'title' => '118 серия',
                'description' => 'Встреча, что пересекла время',
                'slug' => 'episode-118',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3814192&autoplay=0&share=0',
            ],
            [
                'title' => '119 серия',
                'description' => 'Губительный удар',
                'slug' => 'episode-119',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3820497&autoplay=0&share=0',
            ],
            [
                'title' => '120 серия',
                'description' => 'Рассвет',
                'slug' => 'episode-120',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3829990&autoplay=0&share=0',
            ],
            [
                'title' => '121 серия',
                'description' => 'Три проблемы',
                'slug' => 'episode-121',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3844168&autoplay=0&share=0',
            ],
            [
                'title' => '122 серия',
                'description' => 'Чернее чёрного',
                'slug' => 'episode-122',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3851910&autoplay=0&share=0',
            ],
            [
                'title' => '123 серия',
                'description' => 'Воспоминания Неро (часть 1)',
                'slug' => 'episode-123',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3857796&autoplay=0&share=0',
            ],
            [
                'title' => '124 серия',
                'description' => 'Воспоминания Неро (часть 2)',
                'slug' => 'episode-124',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3864834&autoplay=0&share=0',
            ],
            [
                'title' => '125 серия',
                'description' => 'Возвращение',
                'slug' => 'episode-125',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3870390&autoplay=0&share=0',
            ],
            [
                'title' => '126 серия',
                'description' => 'Признание Голубой Розы',
                'slug' => 'episode-126',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3874795&autoplay=0&share=0',
            ],
            [
                'title' => '127 серия',
                'description' => 'Зацепка',
                'slug' => 'episode-127',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3880130&autoplay=0&share=0',
            ],
            [
                'title' => '128 серия',
                'description' => 'В царство Сердца!',
                'slug' => 'episode-128',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3888685&autoplay=0&share=0',
            ],
            [
                'title' => '129 серия',
                'description' => 'Дьявол Мегикула',
                'slug' => 'episode-129',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3897486&autoplay=0&share=0',
            ],
            [
                'title' => '130 серия',
                'description' => 'Новое совещание капитанов',
                'slug' => 'episode-130',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3906510&autoplay=0&share=0',
            ],
            [
                'title' => '131 серия',
                'description' => 'С новой решимостью!',
                'slug' => 'episode-131',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3916620&autoplay=0&share=0',
            ],
            [
                'title' => '132 серия',
                'description' => 'Пробуждение льва',
                'slug' => 'episode-132',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3925819&autoplay=0&share=0',
            ],
            [
                'title' => '133 серия',
                'description' => 'Пробуждение льва: Продолжение',
                'slug' => 'episode-133',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4003342&autoplay=0&share=0',
            ],
            [
                'title' => '134 серия',
                'description' => 'Приглашённые',
                'slug' => 'episode-134',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4012057&autoplay=0&share=0',
            ],
            [
                'title' => '135 серия',
                'description' => 'Тот, кто владеет моим сердцем, моим разумом и душой',
                'slug' => 'episode-135',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4018664&autoplay=0&share=0',
            ],
            [
                'title' => '136 серия',
                'description' => 'Чёрная история морской пучины',
                'slug' => 'episode-136',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4024995&autoplay=0&share=0',
            ],
            [
                'title' => '137 серия',
                'description' => 'Столетний голод Чарми и тысячелетнее одиночество Гордона',
                'slug' => 'episode-137',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4030254&autoplay=0&share=0',
            ],
            [
                'title' => '138 серия',
                'description' => 'Наследник Зары',
                'slug' => 'episode-138',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4037949&autoplay=0&share=0',
            ],
            [
                'title' => '139 серия',
                'description' => 'Ведьма приходит домой',
                'slug' => 'episode-139',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4045214&autoplay=0&share=0',
            ],
            [
                'title' => '140 серия',
                'description' => 'Просьба Юлиуса',
                'slug' => 'episode-140',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4052929&autoplay=0&share=0',
            ],
            [
                'title' => '141 серия',
                'description' => 'Золотая семья',
                'slug' => 'episode-141',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4061514&autoplay=0&share=0',
            ],
            [
                'title' => '142 серия',
                'description' => 'Оставленные',
                'slug' => 'episode-142',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4070414&autoplay=0&share=0',
            ],
            [
                'title' => '143 серия',
                'description' => 'Перекошенные весы',
                'slug' => 'episode-143',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4081582&autoplay=0&share=0',
            ],
            [
                'title' => '144 серия',
                'description' => 'Те, кто желает погибели дьяволу',
                'slug' => 'episode-144',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4090905&autoplay=0&share=0',
            ],
            [
                'title' => '145 серия',
                'description' => 'Отбить своих',
                'slug' => 'episode-145',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4097517&autoplay=0&share=0',
            ],
            [
                'title' => '146 серия',
                'description' => 'Те, кто желает процветания дьяволу',
                'slug' => 'episode-146',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4104035&autoplay=0&share=0',
            ],
            [
                'title' => '147 серия',
                'description' => 'Отчаянный',
                'slug' => 'episode-147',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4110163&autoplay=0&share=0',
            ],
            [
                'title' => '148 серия',
                'description' => 'Стань светом, что разгонит тьму',
                'slug' => 'episode-148',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4116902&autoplay=0&share=0',
            ],
            [
                'title' => '149 серия',
                'description' => 'Два поиска',
                'slug' => 'episode-149',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4123022&autoplay=0&share=0',
            ],
            [
                'title' => '150 серия',
                'description' => 'Испытание девушек',
                'slug' => 'episode-150',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4130319&autoplay=0&share=0',
            ],
            [
                'title' => '151 серия',
                'description' => 'Схватка! Битва капитанов рыцарей чар!',
                'slug' => 'episode-151',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4136748&autoplay=0&share=0',
            ],
            [
                'title' => '152 серия',
                'description' => 'Вперёд, в завтра!',
                'slug' => 'episode-152',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4143437&autoplay=0&share=0',
            ],
            [
                'title' => '153 серия',
                'description' => 'Избранные',
                'slug' => 'episode-153',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4152163&autoplay=0&share=0',
            ],
            [
                'title' => '154 серия',
                'description' => 'Вице-капитан Лангрис',
                'slug' => 'episode-154',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4160778&autoplay=0&share=0',
            ],
            [
                'title' => '155 серия',
                'description' => 'Пять духов хранителей',
                'slug' => 'episode-155',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4167212&autoplay=0&share=0',
            ],
            [
                'title' => '156 серия',
                'description' => 'Пробуждение силы',
                'slug' => 'episode-156',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4174549&autoplay=0&share=0',
            ],
            [
                'title' => '157 серия',
                'description' => 'Пятилистный клевер',
                'slug' => 'episode-157',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4187147&autoplay=0&share=0',
            ],
            [
                'title' => '158 серия',
                'description' => 'Начало надежды и отчаяния',
                'slug' => 'episode-158',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4202545&autoplay=0&share=0',
            ],
            [
                'title' => '159 серия',
                'description' => 'Тихие озёра и лесные тени',
                'slug' => 'episode-159',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4207835&autoplay=0&share=0',
            ],
            [
                'title' => '160 серия',
                'description' => 'Посланник из Королевства Лопаты',
                'slug' => 'episode-160',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4212586&autoplay=0&share=0',
            ],
            [
                'title' => '161 серия',
                'description' => 'Сила Зенона',
                'slug' => 'episode-161',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4217292&autoplay=0&share=0',
            ],
            [
                'title' => '162 серия',
                'description' => 'Начинается Великая Война',
                'slug' => 'episode-162',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4223719&autoplay=0&share=0',
            ],
            [
                'title' => '163 серия',
                'description' => 'Данте против капитана Черных быков',
                'slug' => 'episode-163',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4229458&autoplay=0&share=0',
            ],
            [
                'title' => '164 серия',
                'description' => 'Поле битвы: Королевство Сердца',
                'slug' => 'episode-164',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4234615&autoplay=0&share=0',
            ],
            [
                'title' => '165 серия',
                'description' => 'Водный крестовый поход',
                'slug' => 'episode-165',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4243641&autoplay=0&share=0',
            ],
            [
                'title' => '166 серия',
                'description' => 'Капитан Ями Сукэхиро',
                'slug' => 'episode-166',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4250909&autoplay=0&share=0',
            ],
            [
                'title' => '167 серия',
                'description' => 'Черная клятва',
                'slug' => 'episode-167',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4258013&autoplay=0&share=0',
            ],
            [
                'title' => '168 серия',
                'description' => 'Шевеления сильнейших',
                'slug' => 'episode-168',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4262716&autoplay=0&share=0',
            ],
            [
                'title' => '169 серия',
                'description' => 'Ритуал связывания дьявола',
                'slug' => 'episode-169',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4268593&autoplay=0&share=0',
            ],
            [
                'title' => '170 серия',
                'description' => 'Далекое будущее',
                'slug' => 'episode-170',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=4282660&autoplay=0&share=0',
            ],
            [
                'title' => '1 серия',
                'description' => 'Сильнейший человек',
                'slug' => 'episode-1',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2928990&autoplay=0&share=0',
            ],
            [
                'title' => '2 серия',
                'description' => 'Одинокий Киборг',
                'slug' => 'episode-2',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2928988&autoplay=0&share=0',
            ],
            [
                'title' => '3 серия',
                'description' => 'Навязчивый учёный',
                'slug' => 'episode-3',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2928991&autoplay=0&share=0',
            ],
            [
                'title' => '4 серия',
                'description' => 'Современный ниндзя',
                'slug' => 'episode-4',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2927071&autoplay=0&share=0',
            ],
            [
                'title' => '5 серия',
                'description' => 'Величайший учитель',
                'slug' => 'episode-5',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929000&autoplay=0&share=0',
            ],
            [
                'title' => '6 серия',
                'description' => 'Ужасающий город',
                'slug' => 'episode-6',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929005&autoplay=0&share=0',
            ],
            [
                'title' => '7 серия',
                'description' => 'Потрясающий ученик',
                'slug' => 'episode-7',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929007&autoplay=0&share=0',
            ],
            [
                'title' => '8 серия',
                'description' => 'Глубоководный король',
                'slug' => 'episode-8',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929011&autoplay=0&share=0',
            ],
            [
                'title' => '9 серия',
                'description' => 'Непоколебимая справедливость',
                'slug' => 'episode-9',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2927075&autoplay=0&share=0',
            ],
            [
                'title' => '10 серия',
                'description' => 'Непреодолимая опасность',
                'slug' => 'episode-10',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929014&autoplay=0&share=0',
            ],
            [
                'title' => '11 серия',
                'description' => 'Правитель вселенной',
                'slug' => 'episode-11',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929016&autoplay=0&share=0',
            ],
            [
                'title' => '12 серия',
                'description' => 'Сильнейший герой',
                'slug' => 'episode-12',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=2929015&autoplay=0&share=0',
            ],
            [
                'title' => '1 серия',
                'description' => 'Возвращение героя',
                'slug' => 'episode-1',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3589820&autoplay=0&share=0',
            ],
            [
                'title' => '2 серия',
                'description' => 'Человек-Монстр',
                'slug' => 'episode-2',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3594742&autoplay=0&share=0',
            ],
            [
                'title' => '3 серия',
                'description' => 'Охота начинается',
                'slug' => 'episode-3',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3598660&autoplay=0&share=0',
            ],
            [
                'title' => '4 серия',
                'description' => 'Стальная бита',
                'slug' => 'episode-4',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3604120&autoplay=0&share=0',
            ],
            [
                'title' => '5 серия',
                'description' => 'Турнир боевых искусств',
                'slug' => 'episode-5',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3608092&autoplay=0&share=0',
            ],
            [
                'title' => '6 серия',
                'description' => 'Восстание монстров',
                'slug' => 'episode-6',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3612635&autoplay=0&share=0',
            ],
            [
                'title' => '7 серия',
                'description' => 'Герои Класса S',
                'slug' => 'episode-7',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3616833&autoplay=0&share=0',
            ],
            [
                'title' => '8 серия',
                'description' => 'Сопротивление сильных',
                'slug' => 'episode-8',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3622427&autoplay=0&share=0',
            ],
            [
                'title' => '9 серия',
                'description' => 'Сильные неприятности',
                'slug' => 'episode-9',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3631443&autoplay=0&share=0',
            ],
            [
                'title' => '10 серия',
                'description' => 'Окруженное правосудие',
                'slug' => 'episode-10',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3635380&autoplay=0&share=0',
            ],
            [
                'title' => '11 серия',
                'description' => 'Виды гордости',
                'slug' => 'episode-11',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3639928&autoplay=0&share=0',
            ],
            [
                'title' => '12 серия',
                'description' => 'Пора прибраться за учеником',
                'slug' => 'episode-12',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3644612&autoplay=0&share=0',
            ],











            [
                'title' => '1 серия',
                'description' => 'Жестокость',
                'slug' => 'episode-1',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3588208&autoplay=0&share=0',
            ],
            [
                'title' => '2 серия',
                'description' => 'Учитель Саконджи Урокодаки',
                'slug' => 'episode-2',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3592600&autoplay=0&share=0',
            ],
            [
                'title' => '3 серия',
                'description' => 'Сабито и Макомо',
                'slug' => 'episode-3',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3596890&autoplay=0&share=0',
            ],
            [
                'title' => '4 серия',
                'description' => 'Финальный отбор',
                'slug' => 'episode-4',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3601844&autoplay=0&share=0',
            ],
            [
                'title' => '5 серия',
                'description' => 'Моя собственная сталь',
                'slug' => 'episode-5',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3606701&autoplay=0&share=0',
            ],
            [
                'title' => '6 серия',
                'description' => 'Мечник, сопровождающий демона',
                'slug' => 'episode-6',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3610420&autoplay=0&share=0',
            ],
            [
                'title' => '7 серия',
                'description' => 'Кибуцуджи Мудзан',
                'slug' => 'episode-7',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3615315&autoplay=0&share=0',
            ],
            [
                'title' => '8 серия',
                'description' => 'Запах чарующей крови',
                'slug' => 'episode-8',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3620043&autoplay=0&share=0',
            ],
            [
                'title' => '9 серия',
                'description' => 'Демон тэмари и демон стрелок',
                'slug' => 'episode-9',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3625029&autoplay=0&share=0',
            ],
            [
                'title' => '10 серия',
                'description' => 'Вместе навсегда',
                'slug' => 'episode-10',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3629779&autoplay=0&share=0',
            ],
            [
                'title' => '11 серия',
                'description' => 'Дом с барабанами',
                'slug' => 'episode-11',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3633907&autoplay=0&share=0',
            ],
            [
                'title' => '12 серия',
                'description' => 'Кабан обнажает клыки, Зэницу засыпает',
                'slug' => 'episode-12',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3638322&autoplay=0&share=0',
            ],
            [
                'title' => '13 серия',
                'description' => 'Важнее, чем жизнь',
                'slug' => 'episode-13',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3643123&autoplay=0&share=0',
            ],
            [
                'title' => '14 серия',
                'description' => 'Дом с гербом глицинии',
                'slug' => 'episode-14',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3647000&autoplay=0&share=0',
            ],
            [
                'title' => '15 серия',
                'description' => 'Гора Натагумо',
                'slug' => 'episode-15',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3651275&autoplay=0&share=0',
            ],
            [
                'title' => '16 серия',
                'description' => 'Позволить другому сделать первый шаг',
                'slug' => 'episode-16',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3654474&autoplay=0&share=0',
            ],
            [
                'title' => '17 серия',
                'description' => 'Ты должен кое-что освоить',
                'slug' => 'episode-17',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3662477&autoplay=0&share=0',
            ],
            [
                'title' => '18 серия',
                'description' => 'Поддельные связи',
                'slug' => 'episode-18',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3667476&autoplay=0&share=0',
            ],
            [
                'title' => '19 серия',
                'description' => 'Хиноками',
                'slug' => 'episode-19',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3671757&autoplay=0&share=0',
            ],
            [
                'title' => '20 серия',
                'description' => 'Притворная семья',
                'slug' => 'episode-20',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3675997&autoplay=0&share=0',
            ],
            [
                'title' => '21 серия',
                'description' => 'Против правил отряда',
                'slug' => 'episode-21',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3686345&autoplay=0&share=0',
            ],
            [
                'title' => '22 серия',
                'description' => 'Хозяин особняка',
                'slug' => 'episode-22',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3690978&autoplay=0&share=0',
            ],
            [
                'title' => '23 серия',
                'description' => 'Встреча хашира',
                'slug' => 'episode-23',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3695106&autoplay=0&share=0',
            ],
            [
                'title' => '24 серия',
                'description' => 'Восстановительная тренировка',
                'slug' => 'episode-24',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3701678&autoplay=0&share=0',
            ],
            [
                'title' => '25 серия',
                'description' => 'Тсугуко, Канао Тсуюри',
                'slug' => 'episode-25',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3706251&autoplay=0&share=0',
            ],
            [
                'title' => '26 серия',
                'description' => 'Новое задание',
                'slug' => 'episode-26',
                'video_code' => 'https://video.sibnet.ru/shell.php?videoid=3709924&autoplay=0&share=0',
            ],
        ]);
    }
}
